name: Analyse Dockerfile Workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyse Dockerfile avec Hadolint
        run: |
          docker pull hadolint/hadolint:latest || true
          docker run --rm -i hadolint/hadolint < ./Nouveau_dossier/super_calculator/super_calculator/Dockerfile


