name: Analyse Dockerfile Workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyse Dockerfile avec Hadolint
        run: |
          docker run --rm -i hadolint/hadolint < ./Nouveau_dossier/super_calculator/super_calculator/Dockerfile

     
      - name: Installation Semgrep   
        run: pip install semgrep
      - name: semgrep-action
        uses: returntocorp/semgrep-action@v1
      - name: Analyse statistique de Semgrep
        run: |
          semgrep --config p/python ./Nouveau_dossier/super_calculator/super_calculator/Dockerfile
      
      
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
     
      
     

    


