name: Analysestate Workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyse Dockerfile avec hadolint
        run: |
          docker run --rm -i hadolint/hadolint < ./Nouveau dossier/super_calculator/Dockerfile

